plugins {
    id 'com.ldtteam.tableau.maven-publishing' version '0.0.66'
    id 'com.ldtteam.tableau.curseforge' version '0.0.66'
    id 'com.communi-suggestu.obumbratio' version '0.0.7'
}

platform {
    fabric {
        loaderVersion = rootProject.property('fabric.loader.version')
        apiVersion = rootProject.property('fabric.api.version')
        accessWideners = rootProject.file("common/accesswidener.accesswidener")
    }
}

tableau {
    project {
        modId = "flatcoloredblocks"
        group = "mod.flatcoloredblocks"
        publisher = "chisels-and-bits"
        minecraftVersion = rootProject.property('minecraft.version')
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishToLDTTeamMaven('chisels-and-bits-flatcoloredblocks')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
    curse {
        id = '691037'

        relationships {
            tool('chisels-bits-for-fabric')
        }
    }
}

shaders {
    enable()
    sodium()
    fabric()
}

dependencies {
    modImplementation "com.communi-suggestu.saecularia-caudices:fabric:${project.property('communi.suggestu.saecularia.caudices.version')}"
    include "com.communi-suggestu.saecularia-caudices:fabric:${project.property('communi.suggestu.saecularia.caudices.version')}"

    modImplementation "com.communi-suggestu.scena:fabric:${project.property('communi.suggestu.scena.version')}"
    include "com.communi-suggestu.scena:fabric:${project.property('communi.suggestu.scena.version')}"

    modCompileOnly "mod.chiselsandbits:api:${project.property('chisels.and.bits.version')}"
    modRuntimeOnly "mod.chiselsandbits:fabric:${project.property('chisels.and.bits.version')}"
}