plugins {
    id 'fabric-loom'
    id 'net.darkhax.curseforgegradle'
}

project.ext.remapTaskClass = Class.forName('net.fabricmc.loom.task.RemapJarTask')

project.addCoreProject()

project.dependencies.minecraft "com.mojang:minecraft:${project.minecraftVersion}"
project.dependencies.modImplementation "net.fabricmc:fabric-loader:${project.fabricLoaderVersion}"
project.dependencies.modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabricVersion}+${project.minecraftVersion}"
project.dependencies.modImplementation "com.communi-suggestu.scena:scena-fabric:${project.scenaVersion}"
project.dependencies.modRuntimeOnly "mod.chiselsandbits:chisels-and-bits-fabric:${project.chiselsAndBitsVersion}"

project.dependencies.include "com.communi-suggestu.scena:scena-fabric:${project.scenaVersion}"

project.dependencies.mappings loom.layered() { layer ->
    layer.officialMojangMappings()
    layer.parchment("org.parchmentmc.data:parchment-${project.parchmentMinecraftVersion}:${project.parchmentVersion}@zip")
}

project.loom.accessWidenerPath = project(':common').file("accesswidener.accesswidener")
project.tasks.processResources.from project(':common').file("accesswidener.accesswidener")
setupResourceProcessing(project.sourceSets.main)

project.remapJar.addNestedDependencies = true

project.loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

if ((opc.hasPropertySet("curseApiKey") || opc.hasPropertySet("CURSEAPIKEY"))) {
    task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        apiToken = opc.hasPropertySet("curseApiKey") ? opc.getProperty("curseApiKey") : opc.getProperty("CURSEAPIKEY")

        def mainArtifact = upload("691037", tasks.remapJar)
        opc.getStringListProperty("additionalMinecraftVersions").each { v ->
            mainArtifact.addGameVersion(v)
        }

        mainArtifact.releaseType = opc.hasPropertySet("curseReleaseType") ? opc.getProperty("curseReleaseType") : opc.getProperty("CURSERELEASETYPE")
        if (opc.isFeatureEnabled('reformatedCurseFiles')) {
            def mainArtifactName = rootProject.name
            if (opc.isFeatureEnabled('customCurseFileName')) {
                mainArtifactName = opc.getProperty('customCurseFileName')
            }

            mainArtifact.displayName = mainArtifactName + " - " + project.version + " - " + mainArtifact.releaseType
        }

        mainArtifact.changelog = rootProject.file('build/changelog.md')
        mainArtifact.changelogType = 'markdown'

        dependsOn rootProject.tasks.createChangelog
    }
}

def ideaSyncRunModifier = project.tasks.register("ideaSyncRunModifier") {
    doLast {
        def runConfigurationsDir = project.rootProject.file(".idea/runConfigurations")
        runConfigurationsDir.listFiles().each { file ->
            if (!file.name.endsWith(".xml")) {
                return
            }

            def content = file.text
            def targetContent = "<option name=\"Gradle.BeforeRunTask\" enabled=\"true\" tasks=\"processResources\" externalProjectPath=\"\$PROJECT_DIR\$/fabric\" vmOptions=\"\" scriptParameters=\"-PrunsWithIdea=true\" />"
            def alternativeTarget = "<option enabled=\"true\" externalProjectPath=\"\$PROJECT_DIR\$/fabric\" name=\"Gradle.BeforeRunTask\" scriptParameters=\"-PrunsWithIdea=true\" tasks=\"processResources\" vmOptions=\"\"/>"
            def beforeMarker = "</method>"
            if (content.contains(targetContent) || content.contains(alternativeTarget)) {
                return
            }

            def contentParts = content.split(beforeMarker)
            if (contentParts.size() != 2) {
                return
            }

            def newContent = contentParts[0] + targetContent + beforeMarker + contentParts[1]
            file.write(newContent)
        }
    }
}

tasks.named("ideaSyncTask") {
    finalizedBy(ideaSyncRunModifier)
}

idea {
    module {
        excludeDirs += file("src/main/templates")
    }
}
