plugins {
    id 'com.ldtteam.tableau.common' version '0.0.62'
}

tableau {
    project {
        group = "mod.flatcoloredblocks"
        publisher = "chisels-and-bits"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
}

allprojects {Project project ->
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(project.getProperties().get("java.version")))
        }
    }

    repositories {
        maven {
            name 'Chisels-and-Bits'
            url 'https://ldtteam.jfrog.io/artifactory/chisels-and-bits'
        }
    }
}