### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.debug=false

### Toolchain setup
java.version=21

### Project
type=MOD
license=MIT
author=chisels-and-bits
modId=flatcoloredblocks
description=A mod that generates a selection of simple colored blocks, transparent blocks, and glowing blocks ( all configurable ) for use in building and creative projects. Highly configurable with settings to adjust number of hues, values, and saturation, as well as min/max ranges.

### Minecraft
minecraft.version=1.21.1
minecraft.additionalVersions=

### Parchment
parchment.version=2024.11.13
parchment.minecraftVersion=1.21.1

### Neoforge
neoforge.version=21.1.+

### Fabric
fabric.loader.version=0.16.7
fabric.api.version=0.115.1

### Versioning
local.version=1.21.1-local

### Curse
curse.id.neoforge=238590
curse.id.fabric=691037

### Dependency versioning
jetbrains.annotations.version=+
communi.suggestu.saecularia.caudices.version=[21.1.5,)
communi.suggestu.scena.version=[21.1.11,)
chisels.and.bits.version=1.21.1-local

### Versioning
localVersion=1.21.1-local

# Compatibility layers
compat.shaders.enabled=false
compat.shaders.versions.sodium.version=0.6.5
compat.shaders.versions.sodium.fabric.api=0.4.42+d1308ded19
compat.shaders.versions.sodium.fabric.renderer=3.4.0+acb05a3919
compat.shaders.versions.iris.version=1.8.1
compat.shaders.versions.iris.antlr4.runtime=4.13.1
compat.shaders.versions.iris.glsl.transformer=2.0.1
compat.shaders.versions.iris.jcpp=1.4.14
compat.shaders.versions.embeddium=1.0.11
compat.shaders.versions.monocle=0.1.8
