### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

### Toolchain setup
javaVersion=21

### Versioning
localVersion=1.21.1-local
creator=Chisels&Bits
modId=flatcoloredblocks
description=A mod that generates a selection of simple colored blocks, transparent blocks, and glowing blocks ( all configurable ) for use in building and creative projects. Highly configurable with settings to adjust number of hues, values, and saturation, as well as min/max ranges.
license=MIT

### Dependency versioning
minecraftVersion=1.21.1
additionalMinecraftVersions=
parchmentVersion=2024.11.17
parchmentMinecraftVersion=1.21.1
jetbrainsAnnotationsVersion=23.0.0
fabricLoaderVersion=0.16.9
fabricVersion=0.114.0
forgeVersion=21.1.+
scenaVersion=1.21.1-local
chiselsAndBitsVersion=1.26.1-local

# Metadata
author=Chisels&Bits

# Maven data
githubUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks
gitUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks.git
gitConnectUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks.git
projectUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks

# Versioning schema data.
sourceVersionName=1.20
sourceVersionElementIndex=1
mcVersionElementIndex=1
