### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

### Toolchain setup
javaVersion=17

### Versioning
localVersion=1.0.7-FC
creator=Chisels&Bits
modId=flatcoloredblocks
description=A mod that generates a selection of simple colored blocks, transparent blocks, and glowing blocks ( all configurable ) for use in building and creative projects. Highly configurable with settings to adjust number of hues, values, and saturation, as well as min/max ranges.

### Dependency versioning
minecraftVersion=1.20.4
additionalMinecraftVersions=
parchmentVersion=2023.12.31
parchmentMinecraftVersion=1.20.3
jetbrainsAnnotationsVersion=23.0.0
fabricLoaderVersion=0.15.6
fabricVersion=0.95.4
forgeVersion=20.4.147-beta
scenaVersion=1.0.138
chiselsAndBitsVersion=1.4.152

# Metadata
author=Chisels&Bits

# Maven data
githubUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks
gitUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks.git
gitConnectUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks.git
projectUrl=https://github.com/Chisels-and-Bits/FlatColoredBlocks

# Versioning schema data.
sourceVersionName=1.20
sourceVersionElementIndex=1
mcVersionElementIndex=1
