plugins {
    id 'com.ldtteam.tableau.maven-publishing' version '0.0.63'
}

platform {
    project {
        library()
        accessTransformers.from(rootProject.files('common/accesstransformer.cfg'))
    }
}

tableau {
    project {
        group = "mod.flatcoloredblocks"
        publisher = "flatcoloredblocks"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishToLDTTeamMaven('chisels-and-bits-flatcoloredblocks')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
}

dependencies {
    api "com.communi-suggestu.saecularia-caudices:core:${project.property('communi.suggestu.saecularia.caudices.version')}"
    api "com.communi-suggestu.scena:core:${project.property('communi.suggestu.scena.version')}"

    compileOnly "mod.chiselsandbits:api:${project.property('chisels.and.bits.version')}"
}