plugins {
    id ("net.neoforged.gradle.vanilla")
}

project.minecraft.accessTransformers.file project(":common").file("accesstransformer.cfg")

project.dependencies.implementation "net.minecraft:client:${project.minecraftVersion}"
project.dependencies.implementation "com.communi-suggestu.scena:scena-core:${project.scenaVersion}"
project.dependencies.implementation "mod.chiselsandbits:chisels-and-bits-api:${project.chiselsAndBitsVersion}"

subsystems {
    parchment {
        minecraftVersion = project.parchmentMinecraftVersion
        mappingsVersion = project.parchmentVersion
    }
}

project.sourceSets.main.resources.srcDir "src/datagen/generated"

sourceSets {
    configureEach {
        runs {
            modIdentifier "flatcoloredblocks"
        }
    }
}