modLoader="javafml"
loaderVersion="[4,)"
license="@license@"

[[mods]] #mandatory
modId="@id@"
version="@version@"
displayName="@name@"
authors="@author@"
logoFile="logo-forge.png"
description='''
@description@
'''
[[dependencies.@id@]]
    modId="neoforge" #mandatory
    type="REQUIRED" #mandatory
    versionRange="[@forgeVersion@,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.@id@]]
    modId="minecraft" #mandatory
    type="REQUIRED" #mandatory
    versionRange="[@minecraftVersion@]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.@id@]]
    modId="scena" #mandatory
    type="REQUIRED" #mandatory
    versionRange="@supportedScenaVersionRange@"
    ordering="AFTER"
    side="BOTH"
[[dependencies.@id@]]
    modId="chiselsandbits" #mandatory
    type="OPTIONAL" #mandatory
    versionRange="@supportedCandBVersionRange@"
    ordering="AFTER"
    side="BOTH"