plugins {
    id 'com.ldtteam.tableau.maven-publishing' version '0.0.66'
    id 'com.ldtteam.tableau.curseforge' version '0.0.66'
    id 'com.communi-suggestu.obumbratio' version '0.0.7'
}

platform {
    neoforge {
        version = rootProject.property('neoforge.version')
        accessTransformers.from(rootProject.files("common/accesstransformer.cfg"))
    }
}

tableau {
    project {
        modId = "flatcoloredblocks"
        group = "mod.flatcoloredblocks"
        publisher = "chisels-and-bits"
        minecraftVersion = rootProject.property('minecraft.version')
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishToLDTTeamMaven('chisels-and-bits-flatcoloredblocks')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
    curse {
        id = '238590'

        relationships {
            tool('chisels-bits')
        }
    }
}

shaders {
    enable()
    sodium()
    embeddium()
    neoforge()
}

dependencies {
    includedLibraries "com.communi-suggestu.saecularia-caudices:neoforge:${project.property('communi.suggestu.saecularia.caudices.version')}"
    includedLibraries "com.communi-suggestu.scena:neoforge:${project.property('communi.suggestu.scena.version')}"

    runtimeOnly "mod.chiselsandbits:neoforge:${project.property('chisels.and.bits.version')}"
    compileOnly "mod.chiselsandbits:api:${project.property('chisels.and.bits.version')}"
}
